use_frameworks!

target 'myExtensions_Example' do
  pod 'myExtensions', :path => '../'

  target 'myExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
